Add ERROR tag to wrapper errors so we see them

diff --git a/files/sbin/harmonyd b/files/sbin/harmonyd
--- a/files/sbin/harmonyd
+++ b/files/sbin/harmonyd
@@ -11,7 +11,7 @@ pidfile=/run/$progname/$progname.pid
 exec 1> >(logger --id=$pid -t $progname) 2>&1
 
 if [ ! -d /run/$progname -o ! -w /run/$progname ]; then
-   echo "/run/$progname not a writable directory" >&2
+   echo "ERROR /run/$progname not a writable directory" >&2
    exit 1
 fi
 
@@ -81,6 +81,6 @@ myip
 
 while [ 1 ]; do
   LD_LIBRARY_PATH=. ./harmony -verbosity $VERBOSITY -bootnodes $BN_MA -ip $PUB_IP -port $NODE_PORT -is_genesis -blskey_file "${BLSKEYFILE}" -blspass file:.passphrase
-  echo "harmony died, restarting in 30 seconds" >&2
+  echo "ERROR harmony died, restarting in 30 seconds" >&2
   sleep 30
 done
